baseURL = "https://demo.gethugothemes.com/phantom/site/"
languageCode = "en-us"
title = "Phantom | Personal Resume Template"
theme = "phantom-hugo"
# Default time zone for time stamps; use any valid tz database name: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
timeZone = "America/New_York"
# post pagination
paginate = 6 # see https://gohugo.io/extras/pagination/
# post excerpt
summaryLength = 10 # see https://gohugo.io/content-management/excerpts/
# google analytics
googleAnalytics = "UA-123456-78" # example: UA-123456-78, for more info, read the article https://support.google.com/analytics/answer/1008080?hl=en
# disqus short name
disqusShortname = "themefisher-template" # we use disqus to show comments in blog posts . To install disqus please follow this tutorial https://portfolio.peter-baumgartner.net/2017/09/10/how-to-install-disqus-on-hugo/
# disable language
disableLanguages = [
] # example: ["fr"] for disable french language. see https://gohugo.io/content-management/multilingual/
hasCJKLanguage = false #  If hasCJKLanguage true, auto-detect Chinese/Japanese/Korean Languages in the content. see: https://gohugo.io/getting-started/configuration/#hascjklanguage

############################# Build ##############################
[build]
noJSConfigInAssets = false
useResourceCacheWhen = 'fallback'
[build.buildStats]
enable = true
[[build.cachebusters]]
source = 'assets/.*\.(js|ts|jsx|tsx)'
target = '(js|scripts|javascript)'
[[build.cachebusters]]
source = 'assets/.*\.(css|sass|scss)$'
target = '(css|styles|scss|sass)'
[[build.cachebusters]]
source = 'assets/.*\.(.*)$'
target = '$1'


############################# Outputs ##############################
[outputs]
home = ["HTML", "RSS", "JSON", "WebAppManifest"]

############################# Imaging ##############################
[imaging]
# See https://github.com/disintegration/imaging
# Default JPEG or WebP quality setting. Default is 75.
quality = 90
resampleFilter = "lanczos"

############################# Caches ###############################
[caches]
[caches.images]
dir = ":resourceDir/_gen"
maxAge = "720h"

[caches.assets]
dir = ":resourceDir/_gen"
maxAge = "720h"


############################# Markup ###############################
[markup]
[markup.goldmark.renderer]
unsafe = true

###################### Plugins #############################

# CSS Plugins
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Libre+Baskerville:400,400i|Open+Sans:400,600,700,800"
[[params.plugins.css]]
link = "css/bootstrap.min.css"
[[params.plugins.css]]
link = "css/themefisher-fonts.min.css"
[[params.plugins.css]]
link = "css/owl.carousel.min.css"

# JS Plugins
[[params.plugins.js]]
link = "js/jquery-2.2.4.min.js"
[[params.plugins.js]]
link = "js/bootstrap.min.js"
[[params.plugins.js]]
link = "js/isotope.pkgd.min.js"
[[params.plugins.js]]
link = "js/jquery.nicescroll.min.js"
[[params.plugins.js]]
link = "js/owl.carousel.min.js"
[[params.plugins.js]]
link = "js/jquery.easing.min.js"


############################## Menu ###########################
[[menu.main]]
name = "Welcome"
pre = "tf-dial"
url = "welcome/"
weight = 1

[[menu.main]]
name = "About"
pre = "tf-profile-male"
url = "about/"
weight = 2

[[menu.main]]
name = "Services"
pre = "tf-tools-2"
url = "service/"
weight = 3

[[menu.main]]
name = "Resume"
pre = "tf-tools"
url = "resume/"
weight = 4

[[menu.main]]
name = "Works"
pre = "tf-briefcase2"
url = "works/"
weight = 5

[[menu.main]]
name = "Testimonials"
pre = "tf-chat"
url = "testimonial/"
weight = 6

[[menu.main]]
name = "Contact"
pre = "tf-envelope2"
url = "contact/"
weight = 7


########################## Default Parameters ##################
[params]
logo = "img/phantom.png"
favicon = ""
# dark mode
dark_mode = true
# Preloader
preloader = true
# homepge
homepage_content = "A product designer from England, who focuses on interactive design & A freelance designer focusing on typography & clean interfaces. Also works in Google."
homepage_background = "img/banner.jpg"
# Meta data
description = "This is meta description"
author = "Themefisher"
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io/
# copyright text
copyright = "Designed By [Themefisher](https://themefisher.com/) & Developed By [Gethugothemes](https://gethugothemes.com/)"